### PR TITLE
Update a link

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@rhysje00 ping? perhaps besides merging this, you could also make a new release?

**Comment by rhysje00** [comment]
@fingolfin thank you for fixing this link, I should have resolved this much sooner! I have been working on adding a lot of new [graph constructors](/rhysje00/agt/tree/graph_constructors/) to this package, and I have been delaying any release until I get this up to a good standard. Do you think I should make a new release anyway?

**Comment by fingolfin** [comment]
It wouldn't hurt, then the couple minor fixes added since the last release will be available in the next GAP release, 4.12.2. And if you finish your other changes before, no problem, you can always make more released :-)

**Comment by rhysje00** [comment]
Thanks for the advice, I have went ahead and made a new release with the minor changes. I will continue to work on the rest, and release it in the next version.

**Pull request merged**
